# Generated by Django 4.2.10 on 2026-04-26 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_svg', models.TextField(blank=True)),
                ('color', models.CharField(choices=[('blue', 'Navy Blue'), ('gold', 'Gold'), ('green', 'Green')], default='blue', max_length=20)),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('emerald', 'Emerald Green'), ('gold', 'Gold'), ('blue', 'Navy Blue')], default='emerald', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Shivyan Solutions Pvt. Ltd.', max_length=200)),
                ('company_name_nepali', models.CharField(default='शिव्यान सोलुसन्स प्रा.लि.', max_length=200)),
                ('tagline', models.CharField(default='कौशलम् कार्यसिद्धिनम्', max_length=300)),
                ('tagline_en', models.CharField(default="Nepal's Trusted Tax & Business Consultancy", max_length=300)),
                ('hero_headline', models.CharField(default='Simplifying Tax & Business Compliance', max_length=400)),
                ('hero_subtext', models.TextField(default='Expert guidance in taxation, audit, and business advisory.')),
                ('hero_cta_label', models.CharField(default='आजै सम्पर्क गर्नुहोस्', max_length=100)),
                ('phone', models.CharField(default='9744651716', max_length=20)),
                ('email', models.EmailField(default='Shivyansolutions259@gmail.com', max_length=254)),
                ('address', models.TextField(default='Kathmandu, Nepal')),
                ('office_hours', models.CharField(default='Sunday-Friday: 9:00am - 6:00pm', max_length=200)),
                ('about_text_nepali', models.TextField(default='हामी शिव्यान सोलुसन्स प्रा.लि.मा विशेषज्ञहरूको टोली हौं।')),
                ('about_text_en', models.TextField(default='Our team of certified consultants brings decades of expertise.')),
                ('clients_count', models.PositiveIntegerField(default=500)),
                ('experience_years', models.PositiveIntegerField(default=15)),
                ('retention_percent', models.PositiveIntegerField(default=98)),
                ('services_count', models.PositiveIntegerField(default=9)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('meta_description', models.TextField(blank=True, default='Shivyan Solutions - Tax, Audit & Business Advisory Nepal')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_role', models.CharField(max_length=300)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_svg', models.TextField(blank=True)),
                ('color', models.CharField(choices=[('emerald', 'Green'), ('gold', 'Gold'), ('blue', 'Blue')], default='emerald', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Why Choose Us Points',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_nepali', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_svg', models.TextField(blank=True, help_text="SVG path(s) e.g. <path d='...'/>")),
                ('tags', models.CharField(help_text='Comma-separated: PAN,VAT,IRD', max_length=300)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_cta_card', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicecategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
