# Generated by Django 4.2.10 on 2026-04-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='apple_touch_icon',
            field=models.ImageField(blank=True, help_text='Optional 180×180 PNG for iOS “Add to Home Screen”.', null=True, upload_to='site/branding/%Y/%m'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_name_suffix',
            field=models.CharField(blank=True, default='Pvt. Ltd.', help_text='Short line under the name (e.g. "Pvt. Ltd.") when using text brand.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.FileField(blank=True, help_text='Favicon: .ico or .png (32×32 or larger; browsers will scale).', null=True, upload_to='site/branding/%Y/%m'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Replaces the text+icon mark in the header and footer when set.', null=True, upload_to='site/branding/%Y/%m'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for search engines (optional).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Image for link previews (Open Graph / social). If empty, your logo is used when available.', null=True, upload_to='site/branding/%Y/%m'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(blank=True, help_text='Default browser tab title. Leave empty to use company name.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='X (Twitter) URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn URL'),
        ),
    ]
