# Generated by Django 4.2.10 on 2026-04-29 16:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_branding_seo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistrationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('desired_company_name', models.CharField(max_length=220)),
                ('company_type', models.CharField(blank=True, max_length=120)),
                ('business_nature', models.CharField(blank=True, max_length=180)),
                ('registered_address', models.CharField(blank=True, max_length=255)),
                ('kitta_number', models.CharField(blank=True, help_text='Property kitta number (if applicable)', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In review'), ('docs_missing', 'Docs missing'), ('processed', 'Processed'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'company registration application',
                'verbose_name_plural': 'company registration applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('electricity_bill', 'Electricity bill'), ('lalpurja', 'Property Lalpurja'), ('other', 'Other')], db_index=True, max_length=32)),
                ('label', models.CharField(blank=True, help_text='Optional label for “Other” documents', max_length=160)),
                ('file', models.FileField(upload_to='applications/company_registration/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.companyregistrationapplication')),
            ],
            options={
                'verbose_name': 'application document',
                'verbose_name_plural': 'application documents',
                'ordering': ['doc_type', 'uploaded_at', 'id'],
            },
        ),
    ]
