# Generated by Django 4.2.10 on 2026-04-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_registration_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='doc_type',
            field=models.CharField(choices=[('electricity_bill', 'Electricity bill'), ('lalpurja', 'Property Lalpurja'), ('citizenship', 'Citizenship'), ('photo', 'Photo'), ('signature', 'Signature'), ('other', 'Other')], db_index=True, max_length=32),
        ),
    ]
