# Generated by Django 4.2.10 on 2026-04-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional', max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Deselect to stop sending; use unsubscribe to self-remove.')),
                ('unsubscribe_token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('user_agent', models.TextField(blank=True, default='', editable=False)),
            ],
            options={
                'verbose_name': 'newsletter subscriber',
                'verbose_name_plural': 'newsletter subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
